import Foundation
import Testing
@testable import UsefulBotCore

@Suite struct FacePaletteTests {
    @Test func randomFacesAreAlwaysValid() {
        for seed in stride(from: UInt64(0), through: 5_000, by: 97) {
            let face = FacePalette.randomFace(seed: seed &* 1_764_512_347)
            #expect(FacePalette.isShape(face.shape), "bad shape for seed \(seed)")
            #expect(FacePalette.isColor(face.color), "bad color for seed \(seed)")
        }
    }

    @Test func defaultFacesAreDerivedAndValid() {
        let first = FacePalette.defaultFace(for: "bot-scout")
        let second = FacePalette.defaultFace(for: "bot-scout")
        #expect(first == second)
        #expect(FacePalette.isShape(first.shape))
        #expect(FacePalette.isColor(first.color))
    }

    @Test func defaultFacesMatchTheWebImplementation() {
        // Values generated by shared/bot-face.ts defaultFaceFor. Keep them in
        // step with the web test so Reset agrees across clients.
        #expect(FacePalette.defaultFace(for: "bot-scout") == FacePalette.Face(shape: "blob", color: "orange"))
        #expect(FacePalette.defaultFace(for: "bot-useful") == FacePalette.Face(shape: "drop", color: "ink"))
        #expect(FacePalette.defaultFace(for: String(repeating: "🙂", count: 500))
            == FacePalette.Face(shape: "circle", color: "pink"))
        #expect(FacePalette.defaultFace(for: String(repeating: "~", count: 1000))
            == FacePalette.Face(shape: "circle", color: "blue"))
    }

    @Test func largeTimestampsDoNotProduceNegativeIndices() {
        // The web bug came from int32 wrap-around on Date.now()-scale values.
        let face = FacePalette.randomFace(seed: UInt64(Date().timeIntervalSince1970 * 1000))
        #expect(FacePalette.isShape(face.shape))
        #expect(FacePalette.isColor(face.color))
    }

    @Test func legacyProfilesUseMascotColorsWithoutRewritingStoredImages() throws {
        let json = """
        {"id":"bot-scout","avatarShape":"triangle","avatarColor":"blue","avatarImage":"saved-image","avatarCustom":true}
        """
        let bot = try JSONDecoder().decode(ShellBot.self, from: Data(json.utf8))
        #expect(FacePalette.displayColor(for: bot) == "blue")
        #expect(bot.avatarShape == "triangle")
        #expect(bot.avatarImage == "saved-image")
        var invalidColor = bot
        invalidColor.avatarColor = "not-a-color"
        #expect(FacePalette.displayColor(for: invalidColor) == "ink")
    }

    @Test func defaultBotIsOriginalUntilItsColorIsCustomized() throws {
        let json = """
        {"id":"bot-useful","avatarColor":"blue","avatarCustom":false}
        """
        var bot = try JSONDecoder().decode(ShellBot.self, from: Data(json.utf8))
        #expect(FacePalette.displayColor(for: bot) == "ink")
        bot.avatarCustom = true
        #expect(FacePalette.displayColor(for: bot) == "blue")
    }
}
